name: build
on:
  schedule:
    - cron: '0 9 * * 0' # https://crontab.guru/#0_9_*_*_0
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
